version: 2
jobs:
  lint:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run:
          name: "Code linter"
          command: |
            cargo fmt -- --check
  test:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v15.14.0/node-v15.14.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v15.14.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: "Install node dependencies"
          command: |
            cd tests/fixtures/server-static && npm install
      - run:
          name: "Install openssl"
          command: |
            sudo apt-get update && sudo apt-get install libssl-dev
      - run: cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
